server:
  port: 8880

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mohamedutopios/config-server.git
          default-label: main